server:
  # HTTP listener configurations
  http:
    host: '0.0.0.0'
    port: 9001
    enabled: true

  # Undertow internals
  undertow:
    io-threads: -1
    worker-threads: 300
    buffer-size: 16384 # 1024*16

  # Static asset routing
  static:
    enabled: true

  # Configurations for micro-Routing API
  urouting:
    default-encoding: "UTF-8"
    default-content-type: "application/json"
    # default-content-type: "text/html"
    exception-handler: kikaha.urouting.UnhandledExceptionHandler

  hazelcast:
    config: "conf/hazelcast.xml"

  auth:
    # Distributed Session Management with Hazelcast
    # security-context-factory: kikaha.hazelcast.HazelcastSecurityContextFactory
    security-context-factory: kikaha.core.modules.security.RESTAPISecurityContextFactory

  rules:
    pattern: "/protected/*"
    identity-manager: "custom"
    auth-mechanisms: "basic"
    expected-roles:
    exclude-patterns:

jwt:
  secret: "EFFA813E0EE1340533837C5E96FAEF220DDAE85B5E41EFC32EF210F367F48BFE"
  expires-seconds: 3600