package views.common;

import java.io.IOException;
import com.fizzed.rocker.ForIterator;
import com.fizzed.rocker.RenderingException;
import com.fizzed.rocker.RockerContent;
import com.fizzed.rocker.RockerOutput;
import com.fizzed.rocker.runtime.DefaultRockerTemplate;
import com.fizzed.rocker.runtime.PlainTextUnloadedClassLoader;

/*
 * Auto generated code to render template views/common/error.rocker.html
 * Do not edit this file. Changes will eventually be overwritten by Rocker parser!
 */
public class error extends com.fizzed.rocker.runtime.DefaultRockerModel {

    static public final com.fizzed.rocker.ContentType CONTENT_TYPE = com.fizzed.rocker.ContentType.HTML;
    static public final String TEMPLATE_NAME = "error.rocker.html";
    static public final String TEMPLATE_PACKAGE_NAME = "views.common";
    static public final String HEADER_HASH = "2004300309";
    static public final long MODIFIED_AT = 1494214487000L;
    static public final String[] ARGUMENT_NAMES = { "err" };

    // argument @ [1:2]
    private String err;

    public error err(String err) {
        this.err = err;
        return this;
    }

    public String err() {
        return this.err;
    }

    static public error template(String err) {
        return new error()
            .err(err);
    }

    @Override
    protected DefaultRockerTemplate buildTemplate() throws RenderingException {
        // optimized for convenience (runtime auto reloading enabled if rocker.reloading=true)
        return com.fizzed.rocker.runtime.RockerRuntime.getInstance().getBootstrap().template(this.getClass(), this);
    }

    static public class Template extends com.fizzed.rocker.runtime.DefaultRockerTemplate {

        // <h1>Error 
        static private final byte[] PLAIN_TEXT_0_0;
        // </h1>\n
        static private final byte[] PLAIN_TEXT_1_0;

        static {
            PlainTextUnloadedClassLoader loader = PlainTextUnloadedClassLoader.tryLoad(error.class.getClassLoader(), error.class.getName() + "$PlainText", "UTF-8");
            PLAIN_TEXT_0_0 = loader.tryGet("PLAIN_TEXT_0_0");
            PLAIN_TEXT_1_0 = loader.tryGet("PLAIN_TEXT_1_0");
        }

        // argument @ [1:2]
        protected final String err;

        public Template(error model) {
            super(model);
            __internal.setCharset("UTF-8");
            __internal.setContentType(CONTENT_TYPE);
            __internal.setTemplateName(TEMPLATE_NAME);
            __internal.setTemplatePackageName(TEMPLATE_PACKAGE_NAME);
            this.err = model.err();
        }

        @Override
        protected void __doRender() throws IOException, RenderingException {
            // ValueClosureBegin @ [3:1]
            __internal.aboutToExecutePosInTemplate(3, 1);
            __internal.renderValue(views.common.main.template("Home").__body(() -> {
                // PlainText @ [3:41]
                __internal.aboutToExecutePosInTemplate(3, 41);
                __internal.writeValue(PLAIN_TEXT_0_0);
                // ValueExpression @ [4:11]
                __internal.aboutToExecutePosInTemplate(4, 11);
                __internal.renderValue(err, false);
                // PlainText @ [4:15]
                __internal.aboutToExecutePosInTemplate(4, 15);
                __internal.writeValue(PLAIN_TEXT_1_0);
                // ValueClosureEnd @ [3:1]
                __internal.aboutToExecutePosInTemplate(3, 1);
            }), false); // value closure end @ [3:1]
        }
    }

    private static class PlainText {

        static private final String PLAIN_TEXT_0_0 = "<h1>Error ";
        static private final String PLAIN_TEXT_1_0 = "</h1>\n";

    }

}
