package views;

import java.io.IOException;
import com.fizzed.rocker.ForIterator;
import com.fizzed.rocker.RenderingException;
import com.fizzed.rocker.RockerContent;
import com.fizzed.rocker.RockerOutput;
import com.fizzed.rocker.runtime.DefaultRockerTemplate;
import com.fizzed.rocker.runtime.PlainTextUnloadedClassLoader;
// import @ [1:1]
import myapp.models.Forum;;
// import @ [2:1]
import myapp.models.Post;;
// import @ [3:1]
import myapp.models.User;;

/*
 * Auto generated code to render template views/botredis.rocker.html
 * Do not edit this file. Changes will eventually be overwritten by Rocker parser!
 */
public class botredis extends com.fizzed.rocker.runtime.DefaultRockerModel {

    static public final com.fizzed.rocker.ContentType CONTENT_TYPE = com.fizzed.rocker.ContentType.HTML;
    static public final String TEMPLATE_NAME = "botredis.rocker.html";
    static public final String TEMPLATE_PACKAGE_NAME = "views";
    static public final String HEADER_HASH = "-2045760142";
    static public final long MODIFIED_AT = 1494311306000L;
    static public final String[] ARGUMENT_NAMES = { "forum", "u" };

    // argument @ [5:2]
    private Forum forum;
    // argument @ [5:2]
    private User u;

    public botredis forum(Forum forum) {
        this.forum = forum;
        return this;
    }

    public Forum forum() {
        return this.forum;
    }

    public botredis u(User u) {
        this.u = u;
        return this;
    }

    public User u() {
        return this.u;
    }

    static public botredis template(Forum forum, User u) {
        return new botredis()
            .forum(forum)
            .u(u);
    }

    @Override
    protected DefaultRockerTemplate buildTemplate() throws RenderingException {
        // optimized for convenience (runtime auto reloading enabled if rocker.reloading=true)
        return com.fizzed.rocker.runtime.RockerRuntime.getInstance().getBootstrap().template(this.getClass(), this);
    }

    static public class Template extends com.fizzed.rocker.runtime.DefaultRockerTemplate {

        //     <div class=\"page-header\">\n        <h1>\n            
        static private final byte[] PLAIN_TEXT_0_0;
        // <br>\n            
        static private final byte[] PLAIN_TEXT_1_0;
        // <br>\n            Posts [
        static private final byte[] PLAIN_TEXT_2_0;
        //  + 
        static private final byte[] PLAIN_TEXT_3_0;
        // ]\n        </h1>\n    </div>\n    <ul class=\"list-group\">\n
        static private final byte[] PLAIN_TEXT_4_0;
        //             <li class=\"list-group-item\">\n                Title: <b>
        static private final byte[] PLAIN_TEXT_5_0;
        // </b>\n                <br>\n                Body: 
        static private final byte[] PLAIN_TEXT_6_0;
        // \n                <br>\n                <img src=\"
        static private final byte[] PLAIN_TEXT_7_0;
        // \" class=\"thumbnail\" style=\"width: 140px; height: 140px;\">\n                <br>\n                Created At: 
        static private final byte[] PLAIN_TEXT_8_0;
        // \n\n                <br>\n                <br>\n                Author Name: 
        static private final byte[] PLAIN_TEXT_9_0;
        // \n                <br>\n                Role: 
        static private final byte[] PLAIN_TEXT_10_0;
        // \n                <br>\n                Place: 
        static private final byte[] PLAIN_TEXT_11_0;
        // \" class=\"img-circle\" style=\"width: 140px; height: 140px;\">\n            </li>\n
        static private final byte[] PLAIN_TEXT_12_0;
        //     </ul>\n\n
        static private final byte[] PLAIN_TEXT_13_0;
        //     <ul class=\"pagination\">\n
        static private final byte[] PLAIN_TEXT_14_0;
        //         <li><a href=\"/
        static private final byte[] PLAIN_TEXT_15_0;
        // /1\">&laquo;</a></li>\n
        static private final byte[] PLAIN_TEXT_16_0;
        // \n
        static private final byte[] PLAIN_TEXT_17_0;
        //                 i = +forum.page - 4\n
        static private final byte[] PLAIN_TEXT_18_0;
        //             <li class=\"disabled\"><a href=\"#\">...</a></li>\n
        static private final byte[] PLAIN_TEXT_19_0;
        //                 <li class=\"active\"><span> 
        static private final byte[] PLAIN_TEXT_20_0;
        //  <span class=\"sr-only\">(current)</span></span></li>\n
        static private final byte[] PLAIN_TEXT_21_0;
        //                 <li><a href=\"/
        static private final byte[] PLAIN_TEXT_22_0;
        // /
        static private final byte[] PLAIN_TEXT_23_0;
        // \"> 
        static private final byte[] PLAIN_TEXT_24_0;
        //  </a></li>\n
        static private final byte[] PLAIN_TEXT_25_0;
        //                 <li class=\"disabled\"><a href=\"#\">...</a></li>\n                break;\n
        static private final byte[] PLAIN_TEXT_26_0;
        //             <li><a href=\"/
        static private final byte[] PLAIN_TEXT_27_0;
        //  \">&raquo;</a></li>\n
        static private final byte[] PLAIN_TEXT_28_0;
        //     </ul>\n
        static private final byte[] PLAIN_TEXT_29_0;

        static {
            PlainTextUnloadedClassLoader loader = PlainTextUnloadedClassLoader.tryLoad(botredis.class.getClassLoader(), botredis.class.getName() + "$PlainText", "UTF-8");
            PLAIN_TEXT_0_0 = loader.tryGet("PLAIN_TEXT_0_0");
            PLAIN_TEXT_1_0 = loader.tryGet("PLAIN_TEXT_1_0");
            PLAIN_TEXT_2_0 = loader.tryGet("PLAIN_TEXT_2_0");
            PLAIN_TEXT_3_0 = loader.tryGet("PLAIN_TEXT_3_0");
            PLAIN_TEXT_4_0 = loader.tryGet("PLAIN_TEXT_4_0");
            PLAIN_TEXT_5_0 = loader.tryGet("PLAIN_TEXT_5_0");
            PLAIN_TEXT_6_0 = loader.tryGet("PLAIN_TEXT_6_0");
            PLAIN_TEXT_7_0 = loader.tryGet("PLAIN_TEXT_7_0");
            PLAIN_TEXT_8_0 = loader.tryGet("PLAIN_TEXT_8_0");
            PLAIN_TEXT_9_0 = loader.tryGet("PLAIN_TEXT_9_0");
            PLAIN_TEXT_10_0 = loader.tryGet("PLAIN_TEXT_10_0");
            PLAIN_TEXT_11_0 = loader.tryGet("PLAIN_TEXT_11_0");
            PLAIN_TEXT_12_0 = loader.tryGet("PLAIN_TEXT_12_0");
            PLAIN_TEXT_13_0 = loader.tryGet("PLAIN_TEXT_13_0");
            PLAIN_TEXT_14_0 = loader.tryGet("PLAIN_TEXT_14_0");
            PLAIN_TEXT_15_0 = loader.tryGet("PLAIN_TEXT_15_0");
            PLAIN_TEXT_16_0 = loader.tryGet("PLAIN_TEXT_16_0");
            PLAIN_TEXT_17_0 = loader.tryGet("PLAIN_TEXT_17_0");
            PLAIN_TEXT_18_0 = loader.tryGet("PLAIN_TEXT_18_0");
            PLAIN_TEXT_19_0 = loader.tryGet("PLAIN_TEXT_19_0");
            PLAIN_TEXT_20_0 = loader.tryGet("PLAIN_TEXT_20_0");
            PLAIN_TEXT_21_0 = loader.tryGet("PLAIN_TEXT_21_0");
            PLAIN_TEXT_22_0 = loader.tryGet("PLAIN_TEXT_22_0");
            PLAIN_TEXT_23_0 = loader.tryGet("PLAIN_TEXT_23_0");
            PLAIN_TEXT_24_0 = loader.tryGet("PLAIN_TEXT_24_0");
            PLAIN_TEXT_25_0 = loader.tryGet("PLAIN_TEXT_25_0");
            PLAIN_TEXT_26_0 = loader.tryGet("PLAIN_TEXT_26_0");
            PLAIN_TEXT_27_0 = loader.tryGet("PLAIN_TEXT_27_0");
            PLAIN_TEXT_28_0 = loader.tryGet("PLAIN_TEXT_28_0");
            PLAIN_TEXT_29_0 = loader.tryGet("PLAIN_TEXT_29_0");
        }

        // argument @ [5:2]
        protected final Forum forum;
        // argument @ [5:2]
        protected final User u;

        public Template(botredis model) {
            super(model);
            __internal.setCharset("UTF-8");
            __internal.setContentType(CONTENT_TYPE);
            __internal.setTemplateName(TEMPLATE_NAME);
            __internal.setTemplatePackageName(TEMPLATE_PACKAGE_NAME);
            this.forum = model.forum();
            this.u = model.u();
        }

        @Override
        protected void __doRender() throws IOException, RenderingException {
            // ValueClosureBegin @ [7:1]
            __internal.aboutToExecutePosInTemplate(7, 1);
            __internal.renderValue(views.common.mainbot.template("Home").__body(() -> {
                // PlainText @ [7:44]
                __internal.aboutToExecutePosInTemplate(7, 44);
                __internal.writeValue(PLAIN_TEXT_0_0);
                // ValueExpression @ [10:13]
                __internal.aboutToExecutePosInTemplate(10, 13);
                __internal.renderValue(forum.title, false);
                // PlainText @ [10:25]
                __internal.aboutToExecutePosInTemplate(10, 25);
                __internal.writeValue(PLAIN_TEXT_1_0);
                // ValueExpression @ [11:13]
                __internal.aboutToExecutePosInTemplate(11, 13);
                __internal.renderValue(forum.subtitle, false);
                // PlainText @ [11:28]
                __internal.aboutToExecutePosInTemplate(11, 28);
                __internal.writeValue(PLAIN_TEXT_2_0);
                // ValueExpression @ [12:20]
                __internal.aboutToExecutePosInTemplate(12, 20);
                __internal.renderValue(u.name, false);
                // PlainText @ [12:27]
                __internal.aboutToExecutePosInTemplate(12, 27);
                __internal.writeValue(PLAIN_TEXT_3_0);
                // ValueExpression @ [12:30]
                __internal.aboutToExecutePosInTemplate(12, 30);
                __internal.renderValue(u.age, false);
                // PlainText @ [12:36]
                __internal.aboutToExecutePosInTemplate(12, 36);
                __internal.writeValue(PLAIN_TEXT_4_0);
                // ForBlockBegin @ [16:9]
                __internal.aboutToExecutePosInTemplate(16, 9);
                try {
                    final com.fizzed.rocker.runtime.CollectionForIterator<Post> __forIterator0 = new com.fizzed.rocker.runtime.CollectionForIterator<Post>(forum.posts);
                    while (__forIterator0.hasNext()) {
                        final Post p = __forIterator0.next();
                        try {
                            // PlainText @ [16:38]
                            __internal.aboutToExecutePosInTemplate(16, 38);
                            __internal.writeValue(PLAIN_TEXT_5_0);
                            // ValueExpression @ [18:27]
                            __internal.aboutToExecutePosInTemplate(18, 27);
                            __internal.renderValue(p.title, false);
                            // PlainText @ [18:35]
                            __internal.aboutToExecutePosInTemplate(18, 35);
                            __internal.writeValue(PLAIN_TEXT_6_0);
                            // ValueExpression @ [20:23]
                            __internal.aboutToExecutePosInTemplate(20, 23);
                            __internal.renderValue(p.body, false);
                            // PlainText @ [20:30]
                            __internal.aboutToExecutePosInTemplate(20, 30);
                            __internal.writeValue(PLAIN_TEXT_7_0);
                            // ValueExpression @ [22:27]
                            __internal.aboutToExecutePosInTemplate(22, 27);
                            __internal.renderValue(p.image_url, false);
                            // PlainText @ [22:39]
                            __internal.aboutToExecutePosInTemplate(22, 39);
                            __internal.writeValue(PLAIN_TEXT_8_0);
                            // ValueExpression @ [24:29]
                            __internal.aboutToExecutePosInTemplate(24, 29);
                            __internal.renderValue(p.created_at, false);
                            // PlainText @ [24:42]
                            __internal.aboutToExecutePosInTemplate(24, 42);
                            __internal.writeValue(PLAIN_TEXT_9_0);
                            // ValueExpression @ [28:30]
                            __internal.aboutToExecutePosInTemplate(28, 30);
                            __internal.renderValue(p.author.name, false);
                            // PlainText @ [28:44]
                            __internal.aboutToExecutePosInTemplate(28, 44);
                            __internal.writeValue(PLAIN_TEXT_10_0);
                            // ValueExpression @ [30:23]
                            __internal.aboutToExecutePosInTemplate(30, 23);
                            __internal.renderValue(p.author.role, false);
                            // PlainText @ [30:37]
                            __internal.aboutToExecutePosInTemplate(30, 37);
                            __internal.writeValue(PLAIN_TEXT_11_0);
                            // ValueExpression @ [32:24]
                            __internal.aboutToExecutePosInTemplate(32, 24);
                            __internal.renderValue(p.author.place, false);
                            // PlainText @ [32:39]
                            __internal.aboutToExecutePosInTemplate(32, 39);
                            __internal.writeValue(PLAIN_TEXT_7_0);
                            // ValueExpression @ [34:27]
                            __internal.aboutToExecutePosInTemplate(34, 27);
                            __internal.renderValue(p.author.avatar_url, false);
                            // PlainText @ [34:47]
                            __internal.aboutToExecutePosInTemplate(34, 47);
                            __internal.writeValue(PLAIN_TEXT_12_0);
                            // ForBlockEnd @ [16:9]
                            __internal.aboutToExecutePosInTemplate(16, 9);
                        } catch (com.fizzed.rocker.runtime.ContinueException e) {
                            // support for continuing for loops
                        }
                    } // for end @ [16:9]
                } catch (com.fizzed.rocker.runtime.BreakException e) {
                    // support for breaking for loops
                }
                // PlainText @ [36:10]
                __internal.aboutToExecutePosInTemplate(36, 10);
                __internal.writeValue(PLAIN_TEXT_13_0);
                // IfBlockBegin @ [39:5]
                __internal.aboutToExecutePosInTemplate(39, 5);
                if (forum.pageCount > 1) {
                    // PlainText @ [39:32]
                    __internal.aboutToExecutePosInTemplate(39, 32);
                    __internal.writeValue(PLAIN_TEXT_14_0);
                    // IfBlockBegin @ [41:9]
                    __internal.aboutToExecutePosInTemplate(41, 9);
                    if (forum.page > 1) {
                        // PlainText @ [41:31]
                        __internal.aboutToExecutePosInTemplate(41, 31);
                        __internal.writeValue(PLAIN_TEXT_15_0);
                        // ValueExpression @ [42:23]
                        __internal.aboutToExecutePosInTemplate(42, 23);
                        __internal.renderValue(forum.url, false);
                        // PlainText @ [42:33]
                        __internal.aboutToExecutePosInTemplate(42, 33);
                        __internal.writeValue(PLAIN_TEXT_16_0);
                        // IfBlockEnd @ [41:9]
                        __internal.aboutToExecutePosInTemplate(41, 9);
                    } // if end @ [41:9]
                    // PlainText @ [43:10]
                    __internal.aboutToExecutePosInTemplate(43, 10);
                    __internal.writeValue(PLAIN_TEXT_17_0);
                    // WithBlockBegin @ [45:9]
                    __internal.aboutToExecutePosInTemplate(45, 9);
                    com.fizzed.rocker.runtime.WithBlock.with(1, false, (i) -> {
                        // IfBlockBegin @ [46:13]
                        __internal.aboutToExecutePosInTemplate(46, 13);
                        if (forum.page > 5) {
                            // PlainText @ [46:35]
                            __internal.aboutToExecutePosInTemplate(46, 35);
                            __internal.writeValue(PLAIN_TEXT_18_0);
                            // IfBlockEnd @ [46:13]
                            __internal.aboutToExecutePosInTemplate(46, 13);
                        } // if end @ [46:13]
                        // IfBlockBegin @ [49:13]
                        __internal.aboutToExecutePosInTemplate(49, 13);
                        if (i != 1) {
                            // PlainText @ [49:27]
                            __internal.aboutToExecutePosInTemplate(49, 27);
                            __internal.writeValue(PLAIN_TEXT_19_0);
                            // IfBlockEnd @ [49:13]
                            __internal.aboutToExecutePosInTemplate(49, 13);
                        } // if end @ [49:13]
                        // ForBlockBegin @ [52:13]
                        __internal.aboutToExecutePosInTemplate(52, 13);
                        try {
                            for (Integer j = i; j<=forum.pageCount; j++) {
                                try {
                                    // IfBlockBegin @ [53:17]
                                    __internal.aboutToExecutePosInTemplate(53, 17);
                                    if (forum.page == j) {
                                        // PlainText @ [53:40]
                                        __internal.aboutToExecutePosInTemplate(53, 40);
                                        __internal.writeValue(PLAIN_TEXT_20_0);
                                        // ValueExpression @ [54:43]
                                        __internal.aboutToExecutePosInTemplate(54, 43);
                                        __internal.renderValue(j, false);
                                        // PlainText @ [54:45]
                                        __internal.aboutToExecutePosInTemplate(54, 45);
                                        __internal.writeValue(PLAIN_TEXT_21_0);
                                        // IfBlockElse @ [55:17]
                                        __internal.aboutToExecutePosInTemplate(55, 17);
                                    } else { // else @ [55:17]
                                        // PlainText @ [55:25]
                                        __internal.aboutToExecutePosInTemplate(55, 25);
                                        __internal.writeValue(PLAIN_TEXT_22_0);
                                        // ValueExpression @ [56:31]
                                        __internal.aboutToExecutePosInTemplate(56, 31);
                                        __internal.renderValue(forum.url, false);
                                        // PlainText @ [56:41]
                                        __internal.aboutToExecutePosInTemplate(56, 41);
                                        __internal.writeValue(PLAIN_TEXT_23_0);
                                        // ValueExpression @ [56:42]
                                        __internal.aboutToExecutePosInTemplate(56, 42);
                                        __internal.renderValue(j, false);
                                        // PlainText @ [56:44]
                                        __internal.aboutToExecutePosInTemplate(56, 44);
                                        __internal.writeValue(PLAIN_TEXT_24_0);
                                        // ValueExpression @ [56:47]
                                        __internal.aboutToExecutePosInTemplate(56, 47);
                                        __internal.renderValue(j, false);
                                        // PlainText @ [56:49]
                                        __internal.aboutToExecutePosInTemplate(56, 49);
                                        __internal.writeValue(PLAIN_TEXT_25_0);
                                        // IfBlockEnd @ [53:17]
                                        __internal.aboutToExecutePosInTemplate(53, 17);
                                    } // if end @ [53:17]
                                    // IfBlockBegin @ [58:17]
                                    __internal.aboutToExecutePosInTemplate(58, 17);
                                    if (j == (+forum.page + 4)) {
                                        // PlainText @ [58:47]
                                        __internal.aboutToExecutePosInTemplate(58, 47);
                                        __internal.writeValue(PLAIN_TEXT_26_0);
                                        // IfBlockEnd @ [58:17]
                                        __internal.aboutToExecutePosInTemplate(58, 17);
                                    } // if end @ [58:17]
                                    // ForBlockEnd @ [52:13]
                                    __internal.aboutToExecutePosInTemplate(52, 13);
                                } catch (com.fizzed.rocker.runtime.ContinueException e) {
                                    // support for continuing for loops
                                }
                            } // for end @ [52:13]
                        } catch (com.fizzed.rocker.runtime.BreakException e) {
                            // support for breaking for loops
                        }
                        // IfBlockBegin @ [63:13]
                        __internal.aboutToExecutePosInTemplate(63, 13);
                        if (forum.page != forum.pageCount) {
                            // PlainText @ [63:50]
                            __internal.aboutToExecutePosInTemplate(63, 50);
                            __internal.writeValue(PLAIN_TEXT_27_0);
                            // ValueExpression @ [64:27]
                            __internal.aboutToExecutePosInTemplate(64, 27);
                            __internal.renderValue(forum.url, false);
                            // PlainText @ [64:37]
                            __internal.aboutToExecutePosInTemplate(64, 37);
                            __internal.writeValue(PLAIN_TEXT_23_0);
                            // ValueExpression @ [64:38]
                            __internal.aboutToExecutePosInTemplate(64, 38);
                            __internal.renderValue(forum.pageCount, false);
                            // PlainText @ [64:54]
                            __internal.aboutToExecutePosInTemplate(64, 54);
                            __internal.writeValue(PLAIN_TEXT_28_0);
                            // IfBlockEnd @ [63:13]
                            __internal.aboutToExecutePosInTemplate(63, 13);
                        } // if end @ [63:13]
                        // WithBlockEnd @ [45:9]
                        __internal.aboutToExecutePosInTemplate(45, 9);
                    }); // with end @ [45:9]
                    // PlainText @ [66:10]
                    __internal.aboutToExecutePosInTemplate(66, 10);
                    __internal.writeValue(PLAIN_TEXT_29_0);
                    // IfBlockEnd @ [39:5]
                    __internal.aboutToExecutePosInTemplate(39, 5);
                } // if end @ [39:5]
                // ValueClosureEnd @ [7:1]
                __internal.aboutToExecutePosInTemplate(7, 1);
            }), false); // value closure end @ [7:1]
            // PlainText @ [69:2]
            __internal.aboutToExecutePosInTemplate(69, 2);
            __internal.writeValue(PLAIN_TEXT_17_0);
        }
    }

    private static class PlainText {

        static private final String PLAIN_TEXT_0_0 = "    <div class=\"page-header\">\n        <h1>\n            ";
        static private final String PLAIN_TEXT_1_0 = "<br>\n            ";
        static private final String PLAIN_TEXT_2_0 = "<br>\n            Posts [";
        static private final String PLAIN_TEXT_3_0 = " + ";
        static private final String PLAIN_TEXT_4_0 = "]\n        </h1>\n    </div>\n    <ul class=\"list-group\">\n";
        static private final String PLAIN_TEXT_5_0 = "            <li class=\"list-group-item\">\n                Title: <b>";
        static private final String PLAIN_TEXT_6_0 = "</b>\n                <br>\n                Body: ";
        static private final String PLAIN_TEXT_7_0 = "\n                <br>\n                <img src=\"";
        static private final String PLAIN_TEXT_8_0 = "\" class=\"thumbnail\" style=\"width: 140px; height: 140px;\">\n                <br>\n                Created At: ";
        static private final String PLAIN_TEXT_9_0 = "\n\n                <br>\n                <br>\n                Author Name: ";
        static private final String PLAIN_TEXT_10_0 = "\n                <br>\n                Role: ";
        static private final String PLAIN_TEXT_11_0 = "\n                <br>\n                Place: ";
        static private final String PLAIN_TEXT_12_0 = "\" class=\"img-circle\" style=\"width: 140px; height: 140px;\">\n            </li>\n";
        static private final String PLAIN_TEXT_13_0 = "    </ul>\n\n";
        static private final String PLAIN_TEXT_14_0 = "    <ul class=\"pagination\">\n";
        static private final String PLAIN_TEXT_15_0 = "        <li><a href=\"/";
        static private final String PLAIN_TEXT_16_0 = "/1\">&laquo;</a></li>\n";
        static private final String PLAIN_TEXT_17_0 = "\n";
        static private final String PLAIN_TEXT_18_0 = "                i = +forum.page - 4\n";
        static private final String PLAIN_TEXT_19_0 = "            <li class=\"disabled\"><a href=\"#\">...</a></li>\n";
        static private final String PLAIN_TEXT_20_0 = "                <li class=\"active\"><span> ";
        static private final String PLAIN_TEXT_21_0 = " <span class=\"sr-only\">(current)</span></span></li>\n";
        static private final String PLAIN_TEXT_22_0 = "                <li><a href=\"/";
        static private final String PLAIN_TEXT_23_0 = "/";
        static private final String PLAIN_TEXT_24_0 = "\"> ";
        static private final String PLAIN_TEXT_25_0 = " </a></li>\n";
        static private final String PLAIN_TEXT_26_0 = "                <li class=\"disabled\"><a href=\"#\">...</a></li>\n                break;\n";
        static private final String PLAIN_TEXT_27_0 = "            <li><a href=\"/";
        static private final String PLAIN_TEXT_28_0 = " \">&raquo;</a></li>\n";
        static private final String PLAIN_TEXT_29_0 = "    </ul>\n";

    }

}
