package views;

import java.io.IOException;
import com.fizzed.rocker.ForIterator;
import com.fizzed.rocker.RenderingException;
import com.fizzed.rocker.RockerContent;
import com.fizzed.rocker.RockerOutput;
import com.fizzed.rocker.runtime.DefaultRockerTemplate;
import com.fizzed.rocker.runtime.PlainTextUnloadedClassLoader;
// import @ [1:1]
import myapp.models.HazelCast;;

/*
 * Auto generated code to render template views/hazelcast.rocker.html
 * Do not edit this file. Changes will eventually be overwritten by Rocker parser!
 */
public class hazelcast extends com.fizzed.rocker.runtime.DefaultRockerModel {

    static public final com.fizzed.rocker.ContentType CONTENT_TYPE = com.fizzed.rocker.ContentType.HTML;
    static public final String TEMPLATE_NAME = "hazelcast.rocker.html";
    static public final String TEMPLATE_PACKAGE_NAME = "views";
    static public final String HEADER_HASH = "1019189591";
    static public final long MODIFIED_AT = 1493864340000L;
    static public final String[] ARGUMENT_NAMES = { "hc" };

    // argument @ [3:2]
    private HazelCast hc;

    public hazelcast hc(HazelCast hc) {
        this.hc = hc;
        return this;
    }

    public HazelCast hc() {
        return this.hc;
    }

    static public hazelcast template(HazelCast hc) {
        return new hazelcast()
            .hc(hc);
    }

    @Override
    protected DefaultRockerTemplate buildTemplate() throws RenderingException {
        // optimized for convenience (runtime auto reloading enabled if rocker.reloading=true)
        return com.fizzed.rocker.runtime.RockerRuntime.getInstance().getBootstrap().template(this.getClass(), this);
    }

    static public class Template extends com.fizzed.rocker.runtime.DefaultRockerTemplate {

        // <h1>Hazelcast Size: 
        static private final byte[] PLAIN_TEXT_0_0;
        // </h1>\n
        static private final byte[] PLAIN_TEXT_1_0;

        static {
            PlainTextUnloadedClassLoader loader = PlainTextUnloadedClassLoader.tryLoad(hazelcast.class.getClassLoader(), hazelcast.class.getName() + "$PlainText", "UTF-8");
            PLAIN_TEXT_0_0 = loader.tryGet("PLAIN_TEXT_0_0");
            PLAIN_TEXT_1_0 = loader.tryGet("PLAIN_TEXT_1_0");
        }

        // argument @ [3:2]
        protected final HazelCast hc;

        public Template(hazelcast model) {
            super(model);
            __internal.setCharset("UTF-8");
            __internal.setContentType(CONTENT_TYPE);
            __internal.setTemplateName(TEMPLATE_NAME);
            __internal.setTemplatePackageName(TEMPLATE_PACKAGE_NAME);
            this.hc = model.hc();
        }

        @Override
        protected void __doRender() throws IOException, RenderingException {
            // ValueClosureBegin @ [5:1]
            __internal.aboutToExecutePosInTemplate(5, 1);
            __internal.renderValue(views.common.main.template("Home").__body(() -> {
                // PlainText @ [5:41]
                __internal.aboutToExecutePosInTemplate(5, 41);
                __internal.writeValue(PLAIN_TEXT_0_0);
                // ValueExpression @ [6:21]
                __internal.aboutToExecutePosInTemplate(6, 21);
                __internal.renderValue(hc.size, false);
                // PlainText @ [6:29]
                __internal.aboutToExecutePosInTemplate(6, 29);
                __internal.writeValue(PLAIN_TEXT_1_0);
                // ValueClosureEnd @ [5:1]
                __internal.aboutToExecutePosInTemplate(5, 1);
            }), false); // value closure end @ [5:1]
        }
    }

    private static class PlainText {

        static private final String PLAIN_TEXT_0_0 = "<h1>Hazelcast Size: ";
        static private final String PLAIN_TEXT_1_0 = "</h1>\n";

    }

}
