package views;

import java.io.IOException;
import com.fizzed.rocker.ForIterator;
import com.fizzed.rocker.RenderingException;
import com.fizzed.rocker.RockerContent;
import com.fizzed.rocker.RockerOutput;
import com.fizzed.rocker.runtime.DefaultRockerTemplate;
import com.fizzed.rocker.runtime.PlainTextUnloadedClassLoader;
// import @ [1:1]
import myapp.models.Forum;;
// import @ [2:1]
import myapp.models.Post;;

/*
 * Auto generated code to render template views/hazelcast.rocker.html
 * Do not edit this file. Changes will eventually be overwritten by Rocker parser!
 */
public class hazelcast extends com.fizzed.rocker.runtime.DefaultRockerModel {

    static public final com.fizzed.rocker.ContentType CONTENT_TYPE = com.fizzed.rocker.ContentType.HTML;
    static public final String TEMPLATE_NAME = "hazelcast.rocker.html";
    static public final String TEMPLATE_PACKAGE_NAME = "views";
    static public final String HEADER_HASH = "-109662583";
    static public final long MODIFIED_AT = 1494388232000L;
    static public final String[] ARGUMENT_NAMES = { "forum", "title", "subtitle", "url", "page", "pageCount" };

    // argument @ [4:2]
    private Forum forum;
    // argument @ [4:2]
    private String title;
    // argument @ [4:2]
    private String subtitle;
    // argument @ [4:2]
    private String url;
    // argument @ [4:2]
    private Integer page;
    // argument @ [4:2]
    private Integer pageCount;

    public hazelcast forum(Forum forum) {
        this.forum = forum;
        return this;
    }

    public Forum forum() {
        return this.forum;
    }

    public hazelcast title(String title) {
        this.title = title;
        return this;
    }

    public String title() {
        return this.title;
    }

    public hazelcast subtitle(String subtitle) {
        this.subtitle = subtitle;
        return this;
    }

    public String subtitle() {
        return this.subtitle;
    }

    public hazelcast url(String url) {
        this.url = url;
        return this;
    }

    public String url() {
        return this.url;
    }

    public hazelcast page(Integer page) {
        this.page = page;
        return this;
    }

    public Integer page() {
        return this.page;
    }

    public hazelcast pageCount(Integer pageCount) {
        this.pageCount = pageCount;
        return this;
    }

    public Integer pageCount() {
        return this.pageCount;
    }

    static public hazelcast template(Forum forum, String title, String subtitle, String url, Integer page, Integer pageCount) {
        return new hazelcast()
            .forum(forum)
            .title(title)
            .subtitle(subtitle)
            .url(url)
            .page(page)
            .pageCount(pageCount);
    }

    @Override
    protected DefaultRockerTemplate buildTemplate() throws RenderingException {
        // optimized for convenience (runtime auto reloading enabled if rocker.reloading=true)
        return com.fizzed.rocker.runtime.RockerRuntime.getInstance().getBootstrap().template(this.getClass(), this);
    }

    static public class Template extends com.fizzed.rocker.runtime.DefaultRockerTemplate {

        //     <div class=\"page-header\">\n        <h1>\n            
        static private final byte[] PLAIN_TEXT_0_0;
        // <br>\n            
        static private final byte[] PLAIN_TEXT_1_0;
        // <br>\n        </h1>\n    </div>\n    <ul class=\"list-group\">\n
        static private final byte[] PLAIN_TEXT_2_0;
        //             <li class=\"list-group-item\">\n                Title: <b>
        static private final byte[] PLAIN_TEXT_3_0;
        // </b>\n                <br>\n                Body: 
        static private final byte[] PLAIN_TEXT_4_0;
        // \n                <br>\n                <img src=\"
        static private final byte[] PLAIN_TEXT_5_0;
        // \" class=\"thumbnail\" style=\"width: 140px; height: 140px;\">\n                <br>\n                Created At: 
        static private final byte[] PLAIN_TEXT_6_0;
        // \n\n                <br>\n                <br>\n                Author Name: 
        static private final byte[] PLAIN_TEXT_7_0;
        // \n                <br>\n                Role: 
        static private final byte[] PLAIN_TEXT_8_0;
        // \n                <br>\n                Place: 
        static private final byte[] PLAIN_TEXT_9_0;
        // \" class=\"img-circle\" style=\"width: 140px; height: 140px;\">\n            </li>\n
        static private final byte[] PLAIN_TEXT_10_0;
        //     </ul>\n\n
        static private final byte[] PLAIN_TEXT_11_0;
        //     <ul class=\"pagination\">\n
        static private final byte[] PLAIN_TEXT_12_0;
        //         <li><a href=\"/
        static private final byte[] PLAIN_TEXT_13_0;
        // /1\">&laquo;</a></li>\n
        static private final byte[] PLAIN_TEXT_14_0;
        // \n
        static private final byte[] PLAIN_TEXT_15_0;
        //                 i = +page - 4\n
        static private final byte[] PLAIN_TEXT_16_0;
        //             <li class=\"disabled\"><a href=\"#\">...</a></li>\n
        static private final byte[] PLAIN_TEXT_17_0;
        //                 <li class=\"active\"><span> 
        static private final byte[] PLAIN_TEXT_18_0;
        //  <span class=\"sr-only\">(current)</span></span></li>\n
        static private final byte[] PLAIN_TEXT_19_0;
        //                 <li><a href=\"/
        static private final byte[] PLAIN_TEXT_20_0;
        // /
        static private final byte[] PLAIN_TEXT_21_0;
        // \"> 
        static private final byte[] PLAIN_TEXT_22_0;
        //  </a></li>\n
        static private final byte[] PLAIN_TEXT_23_0;
        //                 <li class=\"disabled\"><a href=\"#\">...</a></li>\n                break;\n
        static private final byte[] PLAIN_TEXT_24_0;
        //             <li><a href=\"/
        static private final byte[] PLAIN_TEXT_25_0;
        //  \">&raquo;</a></li>\n
        static private final byte[] PLAIN_TEXT_26_0;
        //     </ul>\n
        static private final byte[] PLAIN_TEXT_27_0;

        static {
            PlainTextUnloadedClassLoader loader = PlainTextUnloadedClassLoader.tryLoad(hazelcast.class.getClassLoader(), hazelcast.class.getName() + "$PlainText", "UTF-8");
            PLAIN_TEXT_0_0 = loader.tryGet("PLAIN_TEXT_0_0");
            PLAIN_TEXT_1_0 = loader.tryGet("PLAIN_TEXT_1_0");
            PLAIN_TEXT_2_0 = loader.tryGet("PLAIN_TEXT_2_0");
            PLAIN_TEXT_3_0 = loader.tryGet("PLAIN_TEXT_3_0");
            PLAIN_TEXT_4_0 = loader.tryGet("PLAIN_TEXT_4_0");
            PLAIN_TEXT_5_0 = loader.tryGet("PLAIN_TEXT_5_0");
            PLAIN_TEXT_6_0 = loader.tryGet("PLAIN_TEXT_6_0");
            PLAIN_TEXT_7_0 = loader.tryGet("PLAIN_TEXT_7_0");
            PLAIN_TEXT_8_0 = loader.tryGet("PLAIN_TEXT_8_0");
            PLAIN_TEXT_9_0 = loader.tryGet("PLAIN_TEXT_9_0");
            PLAIN_TEXT_10_0 = loader.tryGet("PLAIN_TEXT_10_0");
            PLAIN_TEXT_11_0 = loader.tryGet("PLAIN_TEXT_11_0");
            PLAIN_TEXT_12_0 = loader.tryGet("PLAIN_TEXT_12_0");
            PLAIN_TEXT_13_0 = loader.tryGet("PLAIN_TEXT_13_0");
            PLAIN_TEXT_14_0 = loader.tryGet("PLAIN_TEXT_14_0");
            PLAIN_TEXT_15_0 = loader.tryGet("PLAIN_TEXT_15_0");
            PLAIN_TEXT_16_0 = loader.tryGet("PLAIN_TEXT_16_0");
            PLAIN_TEXT_17_0 = loader.tryGet("PLAIN_TEXT_17_0");
            PLAIN_TEXT_18_0 = loader.tryGet("PLAIN_TEXT_18_0");
            PLAIN_TEXT_19_0 = loader.tryGet("PLAIN_TEXT_19_0");
            PLAIN_TEXT_20_0 = loader.tryGet("PLAIN_TEXT_20_0");
            PLAIN_TEXT_21_0 = loader.tryGet("PLAIN_TEXT_21_0");
            PLAIN_TEXT_22_0 = loader.tryGet("PLAIN_TEXT_22_0");
            PLAIN_TEXT_23_0 = loader.tryGet("PLAIN_TEXT_23_0");
            PLAIN_TEXT_24_0 = loader.tryGet("PLAIN_TEXT_24_0");
            PLAIN_TEXT_25_0 = loader.tryGet("PLAIN_TEXT_25_0");
            PLAIN_TEXT_26_0 = loader.tryGet("PLAIN_TEXT_26_0");
            PLAIN_TEXT_27_0 = loader.tryGet("PLAIN_TEXT_27_0");
        }

        // argument @ [4:2]
        protected final Forum forum;
        // argument @ [4:2]
        protected final String title;
        // argument @ [4:2]
        protected final String subtitle;
        // argument @ [4:2]
        protected final String url;
        // argument @ [4:2]
        protected final Integer page;
        // argument @ [4:2]
        protected final Integer pageCount;

        public Template(hazelcast model) {
            super(model);
            __internal.setCharset("UTF-8");
            __internal.setContentType(CONTENT_TYPE);
            __internal.setTemplateName(TEMPLATE_NAME);
            __internal.setTemplatePackageName(TEMPLATE_PACKAGE_NAME);
            this.forum = model.forum();
            this.title = model.title();
            this.subtitle = model.subtitle();
            this.url = model.url();
            this.page = model.page();
            this.pageCount = model.pageCount();
        }

        @Override
        protected void __doRender() throws IOException, RenderingException {
            // ValueClosureBegin @ [6:1]
            __internal.aboutToExecutePosInTemplate(6, 1);
            __internal.renderValue(views.common.main.template("HazelCast").__body(() -> {
                // PlainText @ [6:46]
                __internal.aboutToExecutePosInTemplate(6, 46);
                __internal.writeValue(PLAIN_TEXT_0_0);
                // ValueExpression @ [9:13]
                __internal.aboutToExecutePosInTemplate(9, 13);
                __internal.renderValue(title, false);
                // PlainText @ [9:19]
                __internal.aboutToExecutePosInTemplate(9, 19);
                __internal.writeValue(PLAIN_TEXT_1_0);
                // ValueExpression @ [10:13]
                __internal.aboutToExecutePosInTemplate(10, 13);
                __internal.renderValue(subtitle, false);
                // PlainText @ [10:22]
                __internal.aboutToExecutePosInTemplate(10, 22);
                __internal.writeValue(PLAIN_TEXT_2_0);
                // ForBlockBegin @ [14:9]
                __internal.aboutToExecutePosInTemplate(14, 9);
                try {
                    final com.fizzed.rocker.runtime.CollectionForIterator<Post> __forIterator0 = new com.fizzed.rocker.runtime.CollectionForIterator<Post>(forum.data);
                    while (__forIterator0.hasNext()) {
                        final Post p = __forIterator0.next();
                        try {
                            // PlainText @ [14:37]
                            __internal.aboutToExecutePosInTemplate(14, 37);
                            __internal.writeValue(PLAIN_TEXT_3_0);
                            // ValueExpression @ [16:27]
                            __internal.aboutToExecutePosInTemplate(16, 27);
                            __internal.renderValue(p.title, false);
                            // PlainText @ [16:35]
                            __internal.aboutToExecutePosInTemplate(16, 35);
                            __internal.writeValue(PLAIN_TEXT_4_0);
                            // ValueExpression @ [18:23]
                            __internal.aboutToExecutePosInTemplate(18, 23);
                            __internal.renderValue(p.body, false);
                            // PlainText @ [18:30]
                            __internal.aboutToExecutePosInTemplate(18, 30);
                            __internal.writeValue(PLAIN_TEXT_5_0);
                            // ValueExpression @ [20:27]
                            __internal.aboutToExecutePosInTemplate(20, 27);
                            __internal.renderValue(p.image_url, false);
                            // PlainText @ [20:39]
                            __internal.aboutToExecutePosInTemplate(20, 39);
                            __internal.writeValue(PLAIN_TEXT_6_0);
                            // ValueExpression @ [22:29]
                            __internal.aboutToExecutePosInTemplate(22, 29);
                            __internal.renderValue(p.created_at, false);
                            // PlainText @ [22:42]
                            __internal.aboutToExecutePosInTemplate(22, 42);
                            __internal.writeValue(PLAIN_TEXT_7_0);
                            // ValueExpression @ [26:30]
                            __internal.aboutToExecutePosInTemplate(26, 30);
                            __internal.renderValue(p.author.name, false);
                            // PlainText @ [26:44]
                            __internal.aboutToExecutePosInTemplate(26, 44);
                            __internal.writeValue(PLAIN_TEXT_8_0);
                            // ValueExpression @ [28:23]
                            __internal.aboutToExecutePosInTemplate(28, 23);
                            __internal.renderValue(p.author.role, false);
                            // PlainText @ [28:37]
                            __internal.aboutToExecutePosInTemplate(28, 37);
                            __internal.writeValue(PLAIN_TEXT_9_0);
                            // ValueExpression @ [30:24]
                            __internal.aboutToExecutePosInTemplate(30, 24);
                            __internal.renderValue(p.author.place, false);
                            // PlainText @ [30:39]
                            __internal.aboutToExecutePosInTemplate(30, 39);
                            __internal.writeValue(PLAIN_TEXT_5_0);
                            // ValueExpression @ [32:27]
                            __internal.aboutToExecutePosInTemplate(32, 27);
                            __internal.renderValue(p.author.avatar_url, false);
                            // PlainText @ [32:47]
                            __internal.aboutToExecutePosInTemplate(32, 47);
                            __internal.writeValue(PLAIN_TEXT_10_0);
                            // ForBlockEnd @ [14:9]
                            __internal.aboutToExecutePosInTemplate(14, 9);
                        } catch (com.fizzed.rocker.runtime.ContinueException e) {
                            // support for continuing for loops
                        }
                    } // for end @ [14:9]
                } catch (com.fizzed.rocker.runtime.BreakException e) {
                    // support for breaking for loops
                }
                // PlainText @ [34:10]
                __internal.aboutToExecutePosInTemplate(34, 10);
                __internal.writeValue(PLAIN_TEXT_11_0);
                // IfBlockBegin @ [37:5]
                __internal.aboutToExecutePosInTemplate(37, 5);
                if (pageCount > 1) {
                    // PlainText @ [37:26]
                    __internal.aboutToExecutePosInTemplate(37, 26);
                    __internal.writeValue(PLAIN_TEXT_12_0);
                    // IfBlockBegin @ [39:9]
                    __internal.aboutToExecutePosInTemplate(39, 9);
                    if (page > 1) {
                        // PlainText @ [39:25]
                        __internal.aboutToExecutePosInTemplate(39, 25);
                        __internal.writeValue(PLAIN_TEXT_13_0);
                        // ValueExpression @ [40:23]
                        __internal.aboutToExecutePosInTemplate(40, 23);
                        __internal.renderValue(url, false);
                        // PlainText @ [40:27]
                        __internal.aboutToExecutePosInTemplate(40, 27);
                        __internal.writeValue(PLAIN_TEXT_14_0);
                        // IfBlockEnd @ [39:9]
                        __internal.aboutToExecutePosInTemplate(39, 9);
                    } // if end @ [39:9]
                    // PlainText @ [41:10]
                    __internal.aboutToExecutePosInTemplate(41, 10);
                    __internal.writeValue(PLAIN_TEXT_15_0);
                    // WithBlockBegin @ [43:9]
                    __internal.aboutToExecutePosInTemplate(43, 9);
                    com.fizzed.rocker.runtime.WithBlock.with(1, false, (i) -> {
                        // IfBlockBegin @ [44:13]
                        __internal.aboutToExecutePosInTemplate(44, 13);
                        if (page > 5) {
                            // PlainText @ [44:29]
                            __internal.aboutToExecutePosInTemplate(44, 29);
                            __internal.writeValue(PLAIN_TEXT_16_0);
                            // IfBlockEnd @ [44:13]
                            __internal.aboutToExecutePosInTemplate(44, 13);
                        } // if end @ [44:13]
                        // IfBlockBegin @ [47:13]
                        __internal.aboutToExecutePosInTemplate(47, 13);
                        if (i != 1) {
                            // PlainText @ [47:27]
                            __internal.aboutToExecutePosInTemplate(47, 27);
                            __internal.writeValue(PLAIN_TEXT_17_0);
                            // IfBlockEnd @ [47:13]
                            __internal.aboutToExecutePosInTemplate(47, 13);
                        } // if end @ [47:13]
                        // ForBlockBegin @ [50:13]
                        __internal.aboutToExecutePosInTemplate(50, 13);
                        try {
                            for (Integer j = i; j<=pageCount; j++) {
                                try {
                                    // IfBlockBegin @ [51:17]
                                    __internal.aboutToExecutePosInTemplate(51, 17);
                                    if (page == j) {
                                        // PlainText @ [51:34]
                                        __internal.aboutToExecutePosInTemplate(51, 34);
                                        __internal.writeValue(PLAIN_TEXT_18_0);
                                        // ValueExpression @ [52:43]
                                        __internal.aboutToExecutePosInTemplate(52, 43);
                                        __internal.renderValue(j, false);
                                        // PlainText @ [52:45]
                                        __internal.aboutToExecutePosInTemplate(52, 45);
                                        __internal.writeValue(PLAIN_TEXT_19_0);
                                        // IfBlockElse @ [53:17]
                                        __internal.aboutToExecutePosInTemplate(53, 17);
                                    } else { // else @ [53:17]
                                        // PlainText @ [53:25]
                                        __internal.aboutToExecutePosInTemplate(53, 25);
                                        __internal.writeValue(PLAIN_TEXT_20_0);
                                        // ValueExpression @ [54:31]
                                        __internal.aboutToExecutePosInTemplate(54, 31);
                                        __internal.renderValue(url, false);
                                        // PlainText @ [54:35]
                                        __internal.aboutToExecutePosInTemplate(54, 35);
                                        __internal.writeValue(PLAIN_TEXT_21_0);
                                        // ValueExpression @ [54:36]
                                        __internal.aboutToExecutePosInTemplate(54, 36);
                                        __internal.renderValue(j, false);
                                        // PlainText @ [54:38]
                                        __internal.aboutToExecutePosInTemplate(54, 38);
                                        __internal.writeValue(PLAIN_TEXT_22_0);
                                        // ValueExpression @ [54:41]
                                        __internal.aboutToExecutePosInTemplate(54, 41);
                                        __internal.renderValue(j, false);
                                        // PlainText @ [54:43]
                                        __internal.aboutToExecutePosInTemplate(54, 43);
                                        __internal.writeValue(PLAIN_TEXT_23_0);
                                        // IfBlockEnd @ [51:17]
                                        __internal.aboutToExecutePosInTemplate(51, 17);
                                    } // if end @ [51:17]
                                    // IfBlockBegin @ [56:17]
                                    __internal.aboutToExecutePosInTemplate(56, 17);
                                    if (j == (+page + 4)) {
                                        // PlainText @ [56:41]
                                        __internal.aboutToExecutePosInTemplate(56, 41);
                                        __internal.writeValue(PLAIN_TEXT_24_0);
                                        // IfBlockEnd @ [56:17]
                                        __internal.aboutToExecutePosInTemplate(56, 17);
                                    } // if end @ [56:17]
                                    // ForBlockEnd @ [50:13]
                                    __internal.aboutToExecutePosInTemplate(50, 13);
                                } catch (com.fizzed.rocker.runtime.ContinueException e) {
                                    // support for continuing for loops
                                }
                            } // for end @ [50:13]
                        } catch (com.fizzed.rocker.runtime.BreakException e) {
                            // support for breaking for loops
                        }
                        // IfBlockBegin @ [61:13]
                        __internal.aboutToExecutePosInTemplate(61, 13);
                        if (page != pageCount) {
                            // PlainText @ [61:38]
                            __internal.aboutToExecutePosInTemplate(61, 38);
                            __internal.writeValue(PLAIN_TEXT_25_0);
                            // ValueExpression @ [62:27]
                            __internal.aboutToExecutePosInTemplate(62, 27);
                            __internal.renderValue(url, false);
                            // PlainText @ [62:31]
                            __internal.aboutToExecutePosInTemplate(62, 31);
                            __internal.writeValue(PLAIN_TEXT_21_0);
                            // ValueExpression @ [62:32]
                            __internal.aboutToExecutePosInTemplate(62, 32);
                            __internal.renderValue(pageCount, false);
                            // PlainText @ [62:42]
                            __internal.aboutToExecutePosInTemplate(62, 42);
                            __internal.writeValue(PLAIN_TEXT_26_0);
                            // IfBlockEnd @ [61:13]
                            __internal.aboutToExecutePosInTemplate(61, 13);
                        } // if end @ [61:13]
                        // WithBlockEnd @ [43:9]
                        __internal.aboutToExecutePosInTemplate(43, 9);
                    }); // with end @ [43:9]
                    // PlainText @ [64:10]
                    __internal.aboutToExecutePosInTemplate(64, 10);
                    __internal.writeValue(PLAIN_TEXT_27_0);
                    // IfBlockEnd @ [37:5]
                    __internal.aboutToExecutePosInTemplate(37, 5);
                } // if end @ [37:5]
                // ValueClosureEnd @ [6:1]
                __internal.aboutToExecutePosInTemplate(6, 1);
            }), false); // value closure end @ [6:1]
            // PlainText @ [67:2]
            __internal.aboutToExecutePosInTemplate(67, 2);
            __internal.writeValue(PLAIN_TEXT_15_0);
        }
    }

    private static class PlainText {

        static private final String PLAIN_TEXT_0_0 = "    <div class=\"page-header\">\n        <h1>\n            ";
        static private final String PLAIN_TEXT_1_0 = "<br>\n            ";
        static private final String PLAIN_TEXT_2_0 = "<br>\n        </h1>\n    </div>\n    <ul class=\"list-group\">\n";
        static private final String PLAIN_TEXT_3_0 = "            <li class=\"list-group-item\">\n                Title: <b>";
        static private final String PLAIN_TEXT_4_0 = "</b>\n                <br>\n                Body: ";
        static private final String PLAIN_TEXT_5_0 = "\n                <br>\n                <img src=\"";
        static private final String PLAIN_TEXT_6_0 = "\" class=\"thumbnail\" style=\"width: 140px; height: 140px;\">\n                <br>\n                Created At: ";
        static private final String PLAIN_TEXT_7_0 = "\n\n                <br>\n                <br>\n                Author Name: ";
        static private final String PLAIN_TEXT_8_0 = "\n                <br>\n                Role: ";
        static private final String PLAIN_TEXT_9_0 = "\n                <br>\n                Place: ";
        static private final String PLAIN_TEXT_10_0 = "\" class=\"img-circle\" style=\"width: 140px; height: 140px;\">\n            </li>\n";
        static private final String PLAIN_TEXT_11_0 = "    </ul>\n\n";
        static private final String PLAIN_TEXT_12_0 = "    <ul class=\"pagination\">\n";
        static private final String PLAIN_TEXT_13_0 = "        <li><a href=\"/";
        static private final String PLAIN_TEXT_14_0 = "/1\">&laquo;</a></li>\n";
        static private final String PLAIN_TEXT_15_0 = "\n";
        static private final String PLAIN_TEXT_16_0 = "                i = +page - 4\n";
        static private final String PLAIN_TEXT_17_0 = "            <li class=\"disabled\"><a href=\"#\">...</a></li>\n";
        static private final String PLAIN_TEXT_18_0 = "                <li class=\"active\"><span> ";
        static private final String PLAIN_TEXT_19_0 = " <span class=\"sr-only\">(current)</span></span></li>\n";
        static private final String PLAIN_TEXT_20_0 = "                <li><a href=\"/";
        static private final String PLAIN_TEXT_21_0 = "/";
        static private final String PLAIN_TEXT_22_0 = "\"> ";
        static private final String PLAIN_TEXT_23_0 = " </a></li>\n";
        static private final String PLAIN_TEXT_24_0 = "                <li class=\"disabled\"><a href=\"#\">...</a></li>\n                break;\n";
        static private final String PLAIN_TEXT_25_0 = "            <li><a href=\"/";
        static private final String PLAIN_TEXT_26_0 = " \">&raquo;</a></li>\n";
        static private final String PLAIN_TEXT_27_0 = "    </ul>\n";

    }

}
