package views;

import java.io.IOException;
import com.fizzed.rocker.ForIterator;
import com.fizzed.rocker.RenderingException;
import com.fizzed.rocker.RockerContent;
import com.fizzed.rocker.RockerOutput;
import com.fizzed.rocker.runtime.DefaultRockerTemplate;
import com.fizzed.rocker.runtime.PlainTextUnloadedClassLoader;
// import @ [1:1]
import minerva.User;;

/*
 * Auto generated code to render template views/index.rocker.html
 * Do not edit this file. Changes will eventually be overwritten by Rocker parser!
 */
public class index extends com.fizzed.rocker.runtime.DefaultRockerModel {

    static public final com.fizzed.rocker.ContentType CONTENT_TYPE = com.fizzed.rocker.ContentType.HTML;
    static public final String TEMPLATE_NAME = "index.rocker.html";
    static public final String TEMPLATE_PACKAGE_NAME = "views";
    static public final String HEADER_HASH = "-826206517";
    static public final long MODIFIED_AT = 1493779336000L;
    static public final String[] ARGUMENT_NAMES = { "u" };

    // argument @ [3:2]
    private User u;

    public index u(User u) {
        this.u = u;
        return this;
    }

    public User u() {
        return this.u;
    }

    static public index template(User u) {
        return new index()
            .u(u);
    }

    @Override
    protected DefaultRockerTemplate buildTemplate() throws RenderingException {
        // optimized for convenience (runtime auto reloading enabled if rocker.reloading=true)
        return com.fizzed.rocker.runtime.RockerRuntime.getInstance().getBootstrap().template(this.getClass(), this);
    }

    static public class Template extends com.fizzed.rocker.runtime.DefaultRockerTemplate {

        // <h1>Dynamic data: Name: 
        static private final byte[] PLAIN_TEXT_0_0;
        // </h1>\n<h1>Dynamic data: Age: 
        static private final byte[] PLAIN_TEXT_1_0;
        // </h1>\n
        static private final byte[] PLAIN_TEXT_2_0;

        static {
            PlainTextUnloadedClassLoader loader = PlainTextUnloadedClassLoader.tryLoad(index.class.getClassLoader(), index.class.getName() + "$PlainText", "UTF-8");
            PLAIN_TEXT_0_0 = loader.tryGet("PLAIN_TEXT_0_0");
            PLAIN_TEXT_1_0 = loader.tryGet("PLAIN_TEXT_1_0");
            PLAIN_TEXT_2_0 = loader.tryGet("PLAIN_TEXT_2_0");
        }

        // argument @ [3:2]
        protected final User u;

        public Template(index model) {
            super(model);
            __internal.setCharset("UTF-8");
            __internal.setContentType(CONTENT_TYPE);
            __internal.setTemplateName(TEMPLATE_NAME);
            __internal.setTemplatePackageName(TEMPLATE_PACKAGE_NAME);
            this.u = model.u();
        }

        @Override
        protected void __doRender() throws IOException, RenderingException {
            // ValueClosureBegin @ [5:1]
            __internal.aboutToExecutePosInTemplate(5, 1);
            __internal.renderValue(views.common.main.template("Home").__body(() -> {
                // PlainText @ [5:41]
                __internal.aboutToExecutePosInTemplate(5, 41);
                __internal.writeValue(PLAIN_TEXT_0_0);
                // ValueExpression @ [6:25]
                __internal.aboutToExecutePosInTemplate(6, 25);
                __internal.renderValue(u.name, false);
                // PlainText @ [6:32]
                __internal.aboutToExecutePosInTemplate(6, 32);
                __internal.writeValue(PLAIN_TEXT_1_0);
                // ValueExpression @ [7:24]
                __internal.aboutToExecutePosInTemplate(7, 24);
                __internal.renderValue(u.age, false);
                // PlainText @ [7:30]
                __internal.aboutToExecutePosInTemplate(7, 30);
                __internal.writeValue(PLAIN_TEXT_2_0);
                // ValueClosureEnd @ [5:1]
                __internal.aboutToExecutePosInTemplate(5, 1);
            }), false); // value closure end @ [5:1]
        }
    }

    private static class PlainText {

        static private final String PLAIN_TEXT_0_0 = "<h1>Dynamic data: Name: ";
        static private final String PLAIN_TEXT_1_0 = "</h1>\n<h1>Dynamic data: Age: ";
        static private final String PLAIN_TEXT_2_0 = "</h1>\n";

    }

}
